<?xml version="1.0"?>
<!-- simplified laser scanner, 1 box + 1 cylinder -->
<robot name="laser_scanner" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Hokuyo URG-04LX-UG01 dimensions -->
  <xacro:property name="laser_height" value="0.41" />
  <xacro:property name="laser_width" value="0.5" />
  <xacro:property name="diameter" value="0.42" />
  <xacro:property name="cylinder_height" value="0.29" />
  <xacro:property name="measurement_window_height" value="0.205" />

  <!-- rviz color visualisation -->
  <material name="grey"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material>

  <link name="laser_body">    
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${laser_height/2.0}"/>
      <geometry>
        <box size="${laser_width} ${laser_width} ${laser_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${laser_height/2.0}"/>
      <geometry>
        <box size="${laser_width} ${laser_width} ${laser_height}"/>
      </geometry>
    </collision>
    <!-- inertia missing! -->
  </link>

  <link name="laser">
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${cylinder_height/2.0 - measurement_window_height}"/>
      <geometry>
        <cylinder radius="${diameter/2.0}" length="${cylinder_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${cylinder_height/2.0 - measurement_window_height}"/>
      <geometry>
        <cylinder radius="${diameter}/2.0}" length="${cylinder_height}"/>
      </geometry>
    </collision>
    <!-- inertia missing! -->
  </link>

  <joint name="laser_body_to_laser" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${laser_height + measurement_window_height}"/>
    <parent link="laser_body"/>
    <child link="laser"/>
  </joint>
  
</robot>
